/**
 * Authored FAQ blocks. Six to ten questions per post, every answer 40–80 words.
 *
 * The band is not arbitrary: it is the extraction unit models quote, and the
 * schema enforces it. Answers are written to stand alone, because that is how
 * they get lifted — a reader or a model sees the answer without the question's
 * surrounding context.
 *
 * Only posts whose existing FAQ failed appear here. Where a post already had
 * usable questions, they were kept and expanded rather than replaced.
 */
export const FAQ = {
  "agentic-analytics": [
    { q: "What is agentic analytics?", a: "Agentic analytics describes a system that carries out a multi-step investigation rather than answering a single question. It decomposes what you asked, runs several queries, checks the results against each other, notices when one answer implies a further question, and follows it. Conventional business intelligence stops at the first result and leaves the follow-up to you." },
    { q: "How is agentic analytics different from a chatbot on a dashboard?", a: "A chat interface layered onto existing dashboards translates your question into the queries someone already built. An agentic system treats every question the same way, whether or not anyone anticipated it. The practical test is a why-question: retrofitted assistants answer what happened and stop, because multi-step investigation was never in the architecture." },
    { q: "How can I tell whether a tool is genuinely AI-native?", a: "Three demo tests separate them. Ask a question the existing dashboards do not cover. Ask why something changed rather than what changed. Then change a metric definition and see whether it propagates everywhere immediately or leaves you editing dashboards for a week. Vendors claiming AI-native rarely survive all three." },
    { q: "Does agentic analytics replace dashboards?", a: "No. Dashboards remain good at one thing: a small, stable set of numbers a team watches continuously. What changes is that they stop being the answer to every possible question. Agentic analytics removes the incentive to build a permanent view for every recurring question, which is what causes dashboard sprawl." },
    { q: "What does agentic analytics need to work properly?", a: "Governed metric definitions. An agent that resolves your question against raw column names is guessing, and it will guess fluently and confidently. A semantic layer supplies the business meaning the agent cannot infer from schema alone, which is the difference between an answer you can act on and one you have to verify." },
    { q: "Is agentic analytics suitable for a small team?", a: "It suits small teams particularly well, because the constraint agentic analytics removes is analyst time. A company with no dedicated data staff gains the most from a system that runs an investigation unaided. Larger organisations often gain more from the governance layer than from the autonomy itself." },
  ],

  "ai-analytics-governance": [
    { q: "What is AI contextual governance?", a: "Contextual governance evaluates each AI request in real time against who is asking, what data is involved, the intent behind the request, and the potential impact of the output. It replaces fixed rules that apply identically to every user and every case, which tend to either over-restrict useful work or over-expose sensitive data." },
    { q: "Why do static AI governance rules fail?", a: "Static rules treat all users and use cases the same, so they must be set for the most sensitive case. That either blocks legitimate work for everyone or, when relaxed, exposes data that should have stayed restricted. Neither outcome is a security posture; both are the same rule applied to situations that differ." },
    { q: "What happens when generative BI fabricates an insight?", a: "It produces a confident, well-formatted answer that is wrong, and nothing in the output distinguishes it from a correct one. Traditional data quality tooling does not catch this, because the data was fine and the interpretation was not. A broken pipeline fails loudly; a fabricated insight fails silently." },
    { q: "How do you detect a fabricated insight?", a: "You cannot detect it from the output alone, which is why traceability matters more than review. The system must show which definition resolved the metric, which query ran, and which rows it touched. A tool that returns only prose cannot be checked, and therefore cannot be trusted with a decision that matters." },
    { q: "Is explainability a feature or a governance control?", a: "A governance control. Attribution and a visible query path are what allow a human to overrule the machine, and a human who cannot see the reasoning has no basis on which to overrule anything. Treating explainability as a nice-to-have leaves you with an authority you cannot appeal." },
    { q: "Does governance slow down AI adoption?", a: "Static governance does, because every request routes through the same restrictive path. Contextual governance tends to widen access rather than narrow it: once policies evaluate role and sensitivity separately, low-risk requests stop being blocked by rules written for high-risk ones. The conversation moves from who is allowed in to what each role may see." },
  ],

  "ai-data-analyst": [
    { q: "What is an AI data analyst?", a: "An AI data analyst is a system that answers business questions directly, resolving them against governed metric definitions rather than requiring somebody to write SQL. It handles data preparation, query generation and summarisation, and its usefulness depends far more on the definitions it resolves against than on the underlying model." },
    { q: "What can an AI data analyst reliably automate?", a: "Data preparation, including type inference, deduplication and joining on well-defined keys. Baseline modelling, meaning fitting and comparing standard models against a labelled target. Descriptive summarisation of what moved and by how much. Anomaly flagging when a series leaves its usual range. These are tedious, rule-governed tasks where automation is genuinely reliable." },
    { q: "What can it not do?", a: "Framing the question, because nothing in the data tells you which question matters this quarter. Defining the target, such as what counts as churn and from which date. Judging whether a result is trustworthy, including whether the sample holds or the split leaked. And deciding what to do, which carries the cost of being wrong." },
    { q: "Does an AI data analyst replace a human analyst?", a: "No. It compresses the time between having a question and having a candidate answer. It does not compress the time spent deciding which questions to ask or whether an answer holds. The work that disappears is report retrieval; the work that grows is defining metrics and checking the hard cases." },
    { q: "How much does an AI data analyst cost?", a: "Pricing varies widely by model. Team platforms with trained agents and governance typically run from tens to a few hundred dollars per user per month, and several vendors do not publish pricing at all. Model the cost at three times your current headcount, because per-seat pricing changes character as adoption spreads." },
    { q: "What should I look for in a demo?", a: "Watch whether anyone names what they were trying to find out before the tool produces a recommendation. A demo that moves from data upload straight to insight is showing you the easy part. Ask a question requiring two joins and a comparison, against data the vendor did not prepare in advance." },
  ],

  "analytics-without-a-data-team": [
    { q: "Can a company do analytics without any data analysts?", a: "Yes, and several do. Objection.ai runs eleven unified data sources with no data analysts on staff. What makes it possible is not a cleverer tool but agreed metric definitions plus an interface that does not require SQL. Without the definitions, self-service distributes ambiguity rather than removing the bottleneck." },
    { q: "What breaks first when nobody owns the data?", a: "Numbers start disagreeing between teams, because each was calculated in a different tool from a different filter and no definition was ever written down. Meetings become arguments about whose figure is correct rather than what to do about it. This precedes every other failure and causes most of them." },
    { q: "How do you build a single source of truth without hiring anyone?", a: "Three steps. Connect the sources that hold numbers you act on. Define the shared metrics once, with one formula each, agreed between finance and the operating teams. Then publish those definitions where people work, through role-specific views and a way to ask questions in plain language rather than navigating someone else's dashboard." },
    { q: "Which of those three steps do teams usually skip?", a: "The second. Connecting sources feels like progress and publishing views is visible, but agreeing what revenue means is a slow organisational conversation with no artefact at the end. Skipping it is what produces two revenue numbers in one meeting, and no amount of tooling downstream will resolve that disagreement." },
    { q: "What separates a real single source of truth from a tool that claims it?", a: "Four things: prebuilt connectors covering your actual stack, centralised metric definitions rather than per-dashboard logic, role-based permissions so access can safely widen, and version history so that when a number changes somebody can say why. Tools failing the second point have distributed the inconsistency rather than fixed it." },
    { q: "Is self-service analytics risky without a data team?", a: "There is a real risk, and it is misreading rather than access. A business user with a fast tool and no statistical instinct can reach a wrong conclusion quickly. The mitigation is governed definitions and visible query paths, not gatekeeping, which simply returns you to the queue you were trying to remove." },
  ],

  "dbt": [
    { q: "What is dbt?", a: "dbt is a transformation tool that applies software engineering practice to SQL: version control, automated testing, documentation and dependency management. Analysts write SELECT statements, and dbt handles materialising them in the correct order. It does not move data into your warehouse; it transforms what is already there." },
    { q: "What problem does dbt actually solve?", a: "It makes transformation logic reviewable and repeatable. Before dbt, business logic lived in scattered scripts, scheduled queries and BI-tool calculations with no version history and no tests. The value is less the tool than the discipline it makes cheap to follow, which is why teams notice the change in review quality first." },
    { q: "What is MetricFlow and why does it matter?", a: "MetricFlow is dbt's semantic layer component. It lets you define a metric such as net revenue once, so every downstream query computes it identically rather than each dashboard re-deriving it. That single definition is what stops four teams arriving at four revenue numbers, which is the most common analytics failure." },
    { q: "Is dbt only for large data teams?", a: "No, though the benefit scales with the number of people writing transformations. A single analyst gains version control and tests. A team of ten gains a shared, reviewable definition of business logic. Below roughly one full-time analyst, the setup cost can exceed the benefit for a while." },
    { q: "Does dbt replace a data engineer?", a: "No. dbt covers transformation, which is one part of the job. Ingestion, orchestration, data quality monitoring, access control and cost management all remain. What dbt changes is that analysts can own transformation logic themselves, which frees engineers for the platform work rather than removing the need for them." },
    { q: "When is dbt overkill?", a: "When your data lives in one system, the transformations are trivial, and one person answers every question. In that situation the modelling layer adds ceremony without adding safety. dbt earns its keep once multiple people depend on the same definitions and a wrong number would reach somebody before being caught." },
  ],

  "from-4-hours-to-2-minutes-rcm-analytics": [
    { q: "What did Jindal Healthcare change?", a: "They moved from answering client questions through manual SQL across disconnected systems to running the same analysis on a single governed source of truth. Per-client analysis went from roughly four hours of senior analyst time to about two minutes, and analytics cost fell by ninety percent." },
    { q: "How was protected health information handled?", a: "Jindal masked every piece of protected health information into a separate database before any data moved. The analytics platform pulled from that masked database only, never connected to an EHR, and never saw a patient. The compliance boundary and the analytics boundary were deliberately the same line." },
    { q: "Why does the time saving matter more than the cost saving?", a: "Because it changes which questions get asked. When a deep look costs four hours, teams reserve it for problems they already know exist. When it costs two minutes, chasing a hunch becomes free, and most of the value in analytics sits in the hunches nobody previously had budget to check." },
    { q: "What data sources were involved?", a: "Clearinghouse claim and remittance feeds, meaning the 837s going out and the 835 ERAs coming back, along with the practice management and EHR systems each client billed from, and payer remittance and denial data. Reconciling these by hand was the work that made every question expensive." },
    { q: "Does this apply outside revenue cycle management?", a: "The pattern applies to any business serving multiple clients from separate data environments. The specific pressure in RCM is that every client arrives as its own world, so analytics workload multiplies with the client list. Any agency or managed service with per-client reporting faces the same multiplication." },
    { q: "What was the hardest part of the migration?", a: "Establishing the masking boundary before analytics touched anything, rather than adding controls afterwards. Building the pipeline so that compliance was structural rather than procedural meant the analytics layer could not accidentally see protected data, which removed the need for ongoing review of who looked at what." },
  ],

  "metabase-alternatives": [
    { q: "Why do teams look for a Metabase alternative?", a: "Rarely because of charting. The usual triggers are white-labelling depth, per-tenant isolation when embedding into a product you sell, and governance as the number of dashboards grows. Metabase is unusually easy to stand up, which means teams often outgrow it in a specific direction rather than abandoning it wholesale." },
    { q: "Which Metabase alternative is best for embedded analytics?", a: "It depends on whether you embed for staff or for paying customers. Internal embedding is straightforward and most tools handle it, so optimise for time to first view. Customer-facing embedding is decided by multi-tenancy enforcement and pricing shape long before feature lists become relevant." },
    { q: "What should I check about multi-tenancy?", a: "Whether isolation is enforced at the query layer or by filters somebody has to remember to apply. Filter-based isolation is a data breach waiting for a misconfiguration. Ask how a customer is prevented from seeing another customer's rows if a developer makes a mistake, and accept only a structural answer." },
    { q: "Why is per-seat pricing a problem for embedded analytics?", a: "Because your seat count becomes your customer count. Pricing that looks reasonable for an internal team of twenty becomes the largest line in your product's cost of goods once every customer needs access. Look for capacity or usage pricing, and model it at ten times your current customer base." },
    { q: "Is Metabase's open-source edition enough?", a: "For internal analytics on a moderate scale, frequently yes. The open-source edition costs nothing to license and costs engineering time to operate, which is the real comparison. Teams typically move to a paid tier or another tool over embedding, permissions granularity and support rather than over missing analysis features." },
    { q: "How deep does white labelling need to go?", a: "Further than most evaluations check. Changing the logo and primary colour is the shallow tier. Fonts, chart palettes, loading states, error messages and exported file headers are where the seams show, and a customer who opens developer tools will see the vendor domain regardless of how the interface looks." },
  ],

  "positive-vs-negative-correlation": [
    { q: "What is positive correlation?", a: "Positive correlation means two variables tend to move in the same direction: as one increases, the other increases as well. Advertising spend and impressions usually correlate positively. The relationship describes co-movement only; it says nothing about whether one variable causes the other or whether a third factor drives both." },
    { q: "What is negative correlation?", a: "Negative correlation means two variables move in opposite directions: as one rises, the other falls. Price and units sold frequently correlate negatively. As with positive correlation, the direction is a description of how the two series move together, not evidence that changing one will change the other." },
    { q: "What is the difference between correlation strength and direction?", a: "Direction is whether the relationship is positive or negative. Strength is how tightly the points follow that pattern, usually expressed as a coefficient between minus one and one. Two relationships can share a direction while differing completely in reliability, and conflating the two is the most common reading error." },
    { q: "Does correlation imply causation?", a: "No, and the distinction matters commercially. Two variables can correlate because one causes the other, because both respond to a third factor, or by coincidence in a small sample. Acting on a correlation without establishing a mechanism is how budgets get moved toward channels that were never responsible for the outcome." },
    { q: "How do I visualise a correlation properly?", a: "Use a scatter plot with both variables on their own axes, which lets a reader see the spread as well as the trend. Avoid dual-axis line charts: by choosing the scales you can manufacture an apparent relationship between almost any two series. A real correlation survives being plotted separately." },
    { q: "What sample size do I need before trusting a correlation?", a: "There is no single threshold, but small samples produce spurious correlations easily, and the fewer points you have the stronger an apparent relationship must be before it means anything. Check whether the pattern holds when you split the data by segment or period; genuine relationships usually survive that test." },
  ],

  "types-of-analytics": [
    { q: "What are the four types of analytics?", a: "Descriptive analytics establishes what happened. Diagnostic analytics explains why it happened. Predictive analytics estimates what happens next. Prescriptive analytics recommends an action. They form a sequence rather than a menu, because each stage depends on the one before it being unambiguous." },
    { q: "Which type should a company build first?", a: "Descriptive, almost always. It establishes agreed definitions of what happened, and every later stage inherits those definitions. A predictive model trained on an ambiguous revenue figure produces a forecast that hides the ambiguity behind a confidence interval, which is worse than having no forecast at all." },
    { q: "What is diagnostic analytics and why is it skipped?", a: "Diagnostic analytics isolates why something moved, through segmentation and comparison. It is routinely skipped because it lacks the novelty of prediction, yet it holds most of the practical value. Revenue fell eight percent is descriptive; revenue fell because one channel's close rate halved is what somebody can act on." },
    { q: "When is predictive analytics worth building?", a: "Once your descriptive layer is unambiguous and your diagnostic work has identified which drivers matter. Prediction is comparatively cheap to add at that point and expensive to retrofit onto contested definitions. Buying forecasting capability while three teams still disagree about what a customer is produces precise, unreliable output." },
    { q: "What does prescriptive analytics require?", a: "All three previous stages, plus a model of which levers actually exist. A recommendation is only useful if the organisation can act on it, so prescriptive systems need to know constraints such as budget, capacity and lead time. Without those, the recommendation is a suggestion nobody can implement." },
    { q: "Do smaller companies need all four types?", a: "Most do not, and pursuing all four early is a common way to waste a year. A small company with a trustworthy descriptive layer and the ability to ask diagnostic questions is ahead of a larger one with a forecasting tool built on numbers its own teams dispute." },
  ],

  "will-ai-replace-data-analysts": [
    { q: "Will AI replace data analysts?", a: "No, though it substantially changes the role. AI automates retrieval, data preparation and recurring reporting, which historically consumed most analyst time. What remains is defining metrics, judging whether results hold, and deciding what to do. The role that shrinks is report-writer; the role that grows decides what is true." },
    { q: "What can AI genuinely do today in analytics?", a: "Data cleaning and preprocessing, automated reporting, exploratory analysis, forecasting, anomaly detection and natural-language querying. These are real capabilities rather than marketing claims. What they share is that each has a well-defined input and a checkable output, which is precisely the condition under which automation works reliably." },
    { q: "Will AI automate BI reporting?", a: "The recurring parts, yes. Assembling a weekly or monthly report, pulling the numbers and summarising what moved is largely mechanical. What does not automate is deciding which metrics belong in the report and what a movement means. Reporting splits into an assembly problem and a judgement problem; only the first generalises." },
    { q: "Are dashboards being replaced?", a: "Partly, and by something more useful than another dashboard. Traditional dashboards can only answer questions somebody anticipated when building them, which is why unanticipated questions spawn new views endlessly. What replaces them is asking directly and following up, leaving dashboards for the small stable set of numbers teams watch continuously." },
    { q: "How does generative AI change what an analyst does?", a: "It moves the work from producing answers to governing them. Time previously spent on retrieval relocates to defining metrics so they stick across teams, checking the questions that require knowing where the data lies, and building the pipelines and access controls that decide whether the self-service layer can be trusted." },
    { q: "Which analysts are actually at risk?", a: "Those whose role is genuinely just translating a ticket into SQL. That was always the least durable part of the job and it is the part being automated first. Analysts who own definitions, question results and connect findings to decisions are becoming more valuable as more people query the data." },
  ],

  // ---- batch 2: posts carrying too few questions ----
  "what-is-a-semantic-layer": [
    { q: "What is a semantic layer?", a: "A semantic layer is the governed body of business meaning — the metrics, entities, relationships and verified logic — sitting between raw data and whoever or whatever queries it, so questions resolve to shared definitions instead of guesswork. It can be authored up front in a modelling language or emerge from curated rules and corrections." },
    { q: "Is a semantic data model the same as a semantic layer?", a: "No. A semantic data model is the artefact: entities, attributes and named relationships, often expressed as subject-predicate-object triples. The semantic layer is the system that governs, versions, permissions and serves that model to every query. A model can live in one dashboard tool and be forgotten; a layer is owned infrastructure." },
    { q: "Do I actually need a semantic layer?", a: "If a human reads every number before it drives a decision, you can survive without an explicit one, though you will still pay for inconsistent metrics. If AI agents answer questions directly, you need one, because no human is in the loop to catch an undefined metric before it gets cited." },
    { q: "What is the difference between the dbt Semantic Layer and Cube?", a: "Both let you define a metric once and reuse it. dbt couples the semantic layer to transformation, so metrics live in code beside your models and compile through MetricFlow, which suits teams already running dbt. Cube is headless and decoupled, exposing one governed model to any BI tool, embedded app or agent." },
    { q: "Is the semantic layer obsolete now that models write good SQL?", a: "No. Models did get dramatically better at SQL, but better text-to-SQL raises the floor rather than removing the need to govern what a metric means. Deterministic generation from a governed definition cannot be subtly wrong in the way an inferred query can, and subtle wrongness is the expensive failure." },
    { q: "How is a semantic layer different from a data catalog?", a: "A data catalog tells you what data exists and who owns it. A knowledge graph maps how entities relate. A semantic layer tells you what the numbers mean and how to compute them correctly. They overlap increasingly, but the semantic layer's defining job is governed computation rather than discovery." },
    { q: "Is a semantic layer the same as a metrics layer?", a: "A metrics layer, defining named measures such as net revenue once, is the heart of a semantic layer but not the whole of it. A full semantic layer also carries entities, dimensions, relationships, join logic and governance. Every semantic layer contains a metrics layer; not every metrics layer is complete." },
  ],

  "enterprise-business-intelligence": [
    { q: "What is enterprise business intelligence?", a: "Enterprise BI is business intelligence operating at organisational scale, where the defining constraints are governance, access control and consistency across departments rather than analytical capability. The analysis itself is rarely the hard part; keeping thousands of users working from the same definitions of the same measures is." },
    { q: "How does enterprise BI differ from departmental BI?", a: "Departmental BI answers one team's questions and can tolerate local definitions. Enterprise BI has to reconcile them, because the same measure appears in finance, sales and operations reporting with different filters. The technical requirements overlap heavily; the organisational requirements do not overlap at all." },
    { q: "What usually goes wrong in an enterprise BI rollout?", a: "Buying capability before agreeing definitions. A platform deployed across an organisation that has not settled what revenue or churn means does not resolve the disagreement, it publishes it faster and to more people. The resulting loss of trust is far harder to recover than a delayed rollout." },
    { q: "What governance does enterprise BI require?", a: "Role-based access so leadership sees summaries while operations can drill into detail, a central place where metric definitions live and change, audit trails recording who changed a definition and when, and a clear owner for each measure. Without the last of these, the other three decay within a year." },
    { q: "How should enterprise BI handle sensitive data?", a: "By making the boundary structural rather than procedural. Masking or excluding sensitive fields before data reaches the analytical layer means the platform cannot expose what it never received, which removes the need for continuous review of who accessed what. Policy-based controls alone depend on nobody misconfiguring them." },
    { q: "How do you measure whether enterprise BI is working?", a: "Not by dashboard count or user logins, both of which rise regardless. Useful signals are how often teams dispute a number in a meeting, how long a new question takes to answer, and how many reports are still exported to spreadsheets, which marks precisely where the platform is failing." },
  ],

  "bi-dashboards": [
    { q: "What is a BI dashboard?", a: "A business intelligence dashboard consolidates key measures onto a single screen, using charts and tables so performance can be read at a glance. Modern dashboards are interactive, letting users filter and drill into detail rather than only viewing a fixed summary prepared by somebody else." },
    { q: "How do you build a decision-making dashboard?", a: "Start from the decision, not the data. Name the decision and the person who makes it, work backwards to the three to seven metrics that would change that decision, set the comparison, match the refresh rate to the decision cadence, add thresholds rather than passive displays, and review quarterly for deletion." },
    { q: "What is the difference between a dashboard and a report?", a: "A dashboard is designed for monitoring: current data, read frequently, understood quickly. A report is designed for analysis: historical depth, read occasionally, understood carefully. Problems arise when a dashboard is asked to carry a report's detail, which produces a screen too dense for anyone to read at a glance." },
    { q: "How many metrics should a dashboard show?", a: "Roughly five to seven per view. Beyond that, the eye has nowhere to land and users start ignoring the whole screen rather than prioritising within it. If more measures genuinely matter, that is a signal for several role-specific dashboards rather than one comprehensive display serving nobody well." },
    { q: "Why do most dashboards go unused?", a: "Because they were built from available data rather than from a decision. A dashboard that does not change what anybody does has no reason to be opened, and after a few weeks it is not. The test is not whether people like it but whether anything different happened because of it." },
    { q: "Are BI dashboards useful for small businesses?", a: "Yes, and often more so, because small teams lack analysts to answer questions individually. Cloud tools have removed most of the cost barrier. The discipline matters more at small scale though: with fewer people, a dashboard nobody acts on wastes a larger proportion of available attention." },
  ],

  "logistics-analytics": [
    { q: "What is logistics analytics?", a: "Logistics analytics applies data analysis to the movement of goods: carrier performance, warehouse throughput, route efficiency, delivery reliability and cost per shipment. It typically requires joining carrier systems, warehouse management and order data, which rarely reconcile without deliberate work on identifiers and timestamps." },
    { q: "Why do aggregate on-time rates mislead?", a: "Because logistics performance is about exceptions rather than averages. A ninety-four percent on-time rate conceals which lanes, carriers or customers absorb the failures, and those failures are usually concentrated rather than evenly spread. The aggregate figure is stable and reassuring while a specific route quietly degrades." },
    { q: "What is the difference between logistics and supply chain analytics?", a: "Logistics analytics covers the physical movement and storage of goods. Supply chain analytics is broader, extending upstream into sourcing, supplier risk and demand planning. They share data and overlap in practice, but the questions differ: one asks whether shipments arrive, the other asks whether you ordered the right things." },
    { q: "Which logistics metrics matter most?", a: "On-time in-full delivery, cost per shipment, dwell time, and exception rate by lane and carrier. The specific set depends on where your costs concentrate, but the common failure is tracking only outcomes without tracking the intermediate steps that explain them, which leaves you knowing performance dropped without knowing where." },
    { q: "What data do you need before logistics analytics is useful?", a: "Carrier events, warehouse movements and order records that can be joined on a shared identifier with reconcilable timestamps. Timestamp reconciliation is the underestimated part: systems record events in different time zones and at different points in the process, which quietly corrupts any duration you calculate across them." },
    { q: "Can logistics analytics predict disruptions?", a: "It can flag conditions that historically preceded disruption, such as rising dwell times or a carrier's degrading exception rate, which is genuinely useful. Predicting external shocks is a different problem and far less reliable. The practical value sits in noticing internal degradation early rather than forecasting the unforeseeable." },
  ],

  "what-is-data-modeling": [
    { q: "What is data modeling?", a: "Data modeling is the practice of defining the entities a business cares about, the attributes describing them, and the relationships connecting them. The resulting model determines which questions are cheap to answer, which are expensive, and which are effectively impossible without restructuring what you have already built." },
    { q: "What are the main types of data models?", a: "Conceptual models describe entities and relationships in business language, with no technical detail. Logical models add attributes, keys and normalisation without committing to a database. Physical models specify tables, indexes and data types for a particular system. Each serves a different audience and a different stage of the conversation." },
    { q: "Why does data modeling matter commercially?", a: "Because the model decides what you can ask. A schema that does not record when a subscription changed cannot answer questions about churn timing regardless of which analytics tool sits on top. Modelling decisions made early constrain the questions available years later, usually without anyone remembering why." },
    { q: "What is the difference between data modeling and a semantic layer?", a: "Data modeling structures how information is stored and related. A semantic layer defines what the resulting numbers mean and how metrics are computed from them. You need both: a well-structured warehouse with no agreed definition of revenue still produces several different revenue figures across teams." },
    { q: "What is normalisation and when should you avoid it?", a: "Normalisation removes redundancy by splitting data across related tables, which protects integrity in transactional systems. Analytical workloads often denormalise deliberately, accepting duplication for query speed and simplicity. The right choice depends entirely on whether the system serves writes or reads, and mixing the two rarely serves either well." },
    { q: "Who should own the data model?", a: "Someone accountable for the business meaning, not only the implementation. Models drift when engineers make structural decisions that encode business assumptions nobody validated, such as whether a refunded order still counts. The decision is a business one surfacing as a schema one, and it needs an owner who can settle it." },
  ],

  "apache-superset-alternatives": [
    { q: "What is Apache Superset?", a: "Apache Superset is an open-source business intelligence platform offering charting, dashboards and SQL exploration. It is free to license and self-hosted, which means the cost moves from subscription to engineering time spent on deployment, upgrades, scaling and support rather than disappearing altogether." },
    { q: "Why do teams look for Superset alternatives?", a: "Rarely over charting capability. The usual reasons are the operational burden of self-hosting, governance and permissions granularity, and the absence of vendor support when something breaks in production. Teams tend to leave over what surrounds the analysis rather than over the analysis itself." },
    { q: "Is self-hosting Superset actually cheaper?", a: "It depends on what your engineering time is worth. A zero-cost licence with a day of maintenance a month is not free, and upgrade cycles are where the hidden cost concentrates. Compare total cost including the person who would be paged when a dashboard stops loading at quarter end." },
    { q: "What should I compare Superset alternatives on?", a: "Operational burden, permissions granularity, support model and the modelling layer. Charting is broadly commoditised across the category, so differences there rarely decide anything. The modelling layer matters most: whether metric definitions live centrally or are recreated per dashboard determines whether numbers agree across teams." },
    { q: "Is Superset suitable for embedding into a product?", a: "It is embedded frequently, and the constraints to check are multi-tenancy enforcement and theming depth. Isolation applied by filters rather than at the query layer is fragile, and white-labelling beyond logos and colours often requires meaningful frontend work you should cost before committing." },
    { q: "When is Superset the right choice?", a: "When you have engineering capacity to operate it, your governance requirements are modest, and you value avoiding vendor lock-in or per-seat pricing. It is a strong fit for technical teams serving themselves and a poorer one where non-technical users need to self-serve without support." },
  ],

  "business-intelligence": [
    { q: "What is business intelligence?", a: "Business intelligence is the practice of turning operational data into decisions people actually make. It spans collecting data from source systems, reconciling it into consistent definitions, and presenting it so somebody can act. The discipline long predates the current tooling, and its core problem has never been storage." },
    { q: "How is business intelligence different from analytics?", a: "The terms overlap heavily and are often used interchangeably. Where a distinction is drawn, business intelligence emphasises consistent reporting on agreed measures, while analytics emphasises open-ended investigation. In practice most organisations need both, and treating them as separate purchases tends to produce two disconnected systems." },
    { q: "Why do business intelligence projects fail?", a: "Most fail on definitions rather than technology. Deploying a capable platform across an organisation that has not agreed what revenue or an active customer means produces faster disagreement rather than better decisions. The failure looks technical because it surfaces as conflicting dashboards, but its cause is organisational." },
    { q: "What does a business intelligence stack contain?", a: "Broadly: connectors bringing data from source systems, a warehouse or lakehouse storing it, a transformation layer shaping it, a semantic layer defining what measures mean, and an interface where people ask questions. Teams frequently buy the first, second and fifth while skipping the fourth, which is where consistency lives." },
    { q: "Does business intelligence require a data team?", a: "Increasingly not, though it does require somebody owning definitions. Modern platforms let non-technical users ask questions directly, which removes the retrieval bottleneck. What cannot be removed is the need for an agreed formula behind each measure, and somebody accountable when that formula changes." },
    { q: "How do you know business intelligence is working?", a: "By whether decisions change, not by adoption metrics. Useful signals are how often meetings stall on disputed numbers, how long a genuinely new question takes to answer, and how much reporting still ends up in spreadsheets, which marks exactly where the platform failed to serve somebody." },
  ],

  "database-optimization": [
    { q: "What is database optimization?", a: "Database optimization is the work of making queries return faster and cost less, through indexing, query rewriting, schema design and configuration. It is distinct from scaling, which adds hardware to an unchanged workload, and the two are frequently confused when a system starts to feel slow." },
    { q: "Where do most performance problems come from?", a: "Query plans and indexing rather than hardware. A query scanning a whole table because it cannot use an index will stay slow on a larger machine, just less obviously. Reading the execution plan before provisioning anything is the single highest-value habit in database performance work." },
    { q: "What does adding an index actually cost?", a: "Every index speeds matching reads and slows every write, because the index must be maintained on insert, update and delete. A table with a dozen indexes can have excellent read performance and badly degraded write throughput. The trade-off should be deliberate rather than accumulated one urgent fix at a time." },
    { q: "When should you scale instead of optimize?", a: "When the workload is genuinely larger rather than genuinely inefficient, and when profiling shows the queries are already using appropriate plans. Scaling to compensate for an inefficient join buys time at permanent cost, because the inefficiency remains and the bill recurs every month thereafter." },
    { q: "How does optimization differ in a cloud warehouse?", a: "Columnar warehouses change which optimisations matter. Row-level indexing is largely replaced by partitioning, clustering and reducing scanned data volume, and cost becomes as visible as latency because you are billed for what you scan. Habits from transactional databases transfer poorly and sometimes actively mislead." },
    { q: "How do you find the queries worth optimising?", a: "Rank by total time consumed rather than by individual duration. A query taking two seconds and running ten thousand times a day costs far more than a nightly report taking five minutes. Most databases expose statistics making this ranking straightforward, and the results are frequently surprising." },
  ],
};
